#include "AI.hpp"

namespace ai
{
  static const std::map<State, std::array<State, Value::NB_VALUE>>
      transitionTable = {
          {STARVING,
           {FOOD_ON_CASE, RECEIVE_MSG, NO_CHANGE, NO_CHANGE, MISSING_STONE,
            MISSING_PLAYER, RECEIVE_MSG, NO_CHANGE}},
          {RECEIVE_MSG,
           {NO_CHANGE, MISSING_STONE, LEVEL, MISSING_STONE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, MISSING_STONE}},
          {MISSING_STONE,
           {STONE_ON_CASE, MISSING_PLAYER, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {MISSING_PLAYER,
           {NO_CHANGE, SET_RECIPE, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE}},
          {SET_RECIPE,
           {INCANT, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE}},
          {INCANT,
           {STARVING, MISSING_STONE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {FOOD_ON_CASE,
           {COLLECT_FOOD, FIND_FOOD, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {COLLECT_FOOD,
           {STARVING, FOOD_ON_CASE, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE}},
          {FIND_FOOD,
           {MOVE_TO_FOOD, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {MOVE_TO_FOOD,
           {FOOD_ON_CASE, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {LEVEL,
           {MOVE_TO_TEAMMATE, MISSING_STONE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {MOVE_TO_TEAMMATE,
           {ARRIVED, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE}},
          {ARRIVED,
           {FIX_RECIPE, STARVING, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            STARVING, NO_CHANGE}},
          {FIX_RECIPE,
           {ARRIVED, ARRIVED, NO_CHANGE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE}},
          {STONE_ON_CASE,
           {COLECT_STONE, FIND_STONE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {COLLECT_STONE,
           {STARVING, STONE_ON_CASE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {FIND_STONE,
           {MOVE_TO_STONE, NO_CHANGE, NO_CHANGE, NO_CHANGE, STARVING,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {MOVE_TO_STONE,
           {STONE_ON_CASE, NO_CHANGE, NO_CHANGE, NO_CHANGE, STARVING,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
          {TROLL,
           {MISSING_STONE, MISSING_STONE, NO_CHANGE, NO_CHANGE, NO_CHANGE,
            NO_CHANGE, NO_CHANGE, NO_CHANGE}},
  };

  AI::AI() : m_actionForState();
  {
    initAction();
  }

  AI::AI(AI const &that) : m_actionForState(that.m_actionForState)
  {
  }

  AI::~AI()
  {
  }

  void AI::initAction()
  {
  }
}